name: "Build"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  check:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools curl lld clang cmake
      - name: Setup Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Target to x86_64-unknown-linux-musl
        run: rustup target add x86_64-unknown-linux-musl
      - name: Install cargo-edit
        run: cargo install cargo-edit
      - name: Adjust the version
        run: cargo set-version ${VERSION/v/}
        env:
          VERSION: ${{ github.ref_name }}
      - name: Build the package (Debug)
        run: cargo build --target x86_64-unknown-linux-musl
      - name: "Build the package (Release)"
        run: cargo build --target x86_64-unknown-linux-musl -r
      - name: "Upload the package"
        uses: actions/upload-artifact@v4
        with:
          name: egen
          path: target/x86_64-unknown-linux-musl/debug/egen
      - name: "Create a release"
        run: |
          gh release create ${{ github.ref }} -t ${{ github.ref_name }} \
            --latest --generate-notes target/x86_64-unknown-linux-musl/release/egen
        env:
          GH_TOKEN: ${{ github.token }}
